# Generated by Django 4.2.3 on 2023-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("pokemon_id", models.PositiveIntegerField(unique=True)),
                ("abilities", models.JSONField()),
                ("types", models.JSONField()),
                ("stats", models.JSONField()),
            ],
        ),
    ]
